// <auto-generated />
// <copyright file="Form1.Designer.cs" company="None">
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the 
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is 
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// IN THE SOFTWARE.
//
// Copyright (c) 2017 Jeremy Gibbons. All rights reserved
// </copyright>

namespace PRTGNetFlowUpdater
{
    public partial class FormPRTGMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.Windows.Forms.TreeNode treeNode1 = new System.Windows.Forms.TreeNode("PRTG Configuration");
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.loadToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.saveToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.saveAsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.modeToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.treeViewToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.valueViewToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.aboutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.templatesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.editTemplatesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.panel1 = new System.Windows.Forms.Panel();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.trvConfig = new PRTGNetFlowUpdater.TriStateCBTreeView();
            this.txtDisplay = new System.Windows.Forms.TextBox();
            this.openFileDialog = new System.Windows.Forms.OpenFileDialog();
            this.ctxMenuSensorNode = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.editSingleNodeToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ctxMenuGroupNode = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.editGroupNodeToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ctxMenuDeviceNode = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.editDeviceSensorsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.menuStrip1.SuspendLayout();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            this.ctxMenuSensorNode.SuspendLayout();
            this.ctxMenuGroupNode.SuspendLayout();
            this.ctxMenuDeviceNode.SuspendLayout();
            this.SuspendLayout();
            // 
            // menuStrip1
            // 
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.fileToolStripMenuItem,
            this.modeToolStripMenuItem,
            this.aboutToolStripMenuItem,
            this.templatesToolStripMenuItem});
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(853, 24);
            this.menuStrip1.TabIndex = 0;
            this.menuStrip1.Text = "menuStrip1";
            // 
            // fileToolStripMenuItem
            // 
            this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.loadToolStripMenuItem,
            this.saveToolStripMenuItem,
            this.saveAsToolStripMenuItem});
            this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
            this.fileToolStripMenuItem.Size = new System.Drawing.Size(37, 20);
            this.fileToolStripMenuItem.Text = "File";
            // 
            // loadToolStripMenuItem
            // 
            this.loadToolStripMenuItem.Name = "loadToolStripMenuItem";
            this.loadToolStripMenuItem.Size = new System.Drawing.Size(123, 22);
            this.loadToolStripMenuItem.Text = "Load";
            this.loadToolStripMenuItem.Click += new System.EventHandler(this.LoadToolStripMenuItem_Click);
            // 
            // saveToolStripMenuItem
            // 
            this.saveToolStripMenuItem.Name = "saveToolStripMenuItem";
            this.saveToolStripMenuItem.Size = new System.Drawing.Size(123, 22);
            this.saveToolStripMenuItem.Text = "Save";
            // 
            // saveAsToolStripMenuItem
            // 
            this.saveAsToolStripMenuItem.Name = "saveAsToolStripMenuItem";
            this.saveAsToolStripMenuItem.Size = new System.Drawing.Size(123, 22);
            this.saveAsToolStripMenuItem.Text = "Save As...";
            // 
            // modeToolStripMenuItem
            // 
            this.modeToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.treeViewToolStripMenuItem,
            this.valueViewToolStripMenuItem});
            this.modeToolStripMenuItem.Name = "modeToolStripMenuItem";
            this.modeToolStripMenuItem.Size = new System.Drawing.Size(50, 20);
            this.modeToolStripMenuItem.Text = "Mode";
            // 
            // treeViewToolStripMenuItem
            // 
            this.treeViewToolStripMenuItem.Checked = true;
            this.treeViewToolStripMenuItem.CheckOnClick = true;
            this.treeViewToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
            this.treeViewToolStripMenuItem.Name = "treeViewToolStripMenuItem";
            this.treeViewToolStripMenuItem.Size = new System.Drawing.Size(130, 22);
            this.treeViewToolStripMenuItem.Text = "Tree View";
            this.treeViewToolStripMenuItem.Click += new System.EventHandler(this.treeViewToolStripMenuItem_Click);
            // 
            // valueViewToolStripMenuItem
            // 
            this.valueViewToolStripMenuItem.Name = "valueViewToolStripMenuItem";
            this.valueViewToolStripMenuItem.Size = new System.Drawing.Size(130, 22);
            this.valueViewToolStripMenuItem.Text = "Value View";
            this.valueViewToolStripMenuItem.Click += new System.EventHandler(this.valueViewToolStripMenuItem_Click);
            // 
            // aboutToolStripMenuItem
            // 
            this.aboutToolStripMenuItem.Name = "aboutToolStripMenuItem";
            this.aboutToolStripMenuItem.Size = new System.Drawing.Size(52, 20);
            this.aboutToolStripMenuItem.Text = "About";
            // 
            // templatesToolStripMenuItem
            // 
            this.templatesToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.editTemplatesToolStripMenuItem});
            this.templatesToolStripMenuItem.Name = "templatesToolStripMenuItem";
            this.templatesToolStripMenuItem.Size = new System.Drawing.Size(73, 20);
            this.templatesToolStripMenuItem.Text = "Templates";
            // 
            // editTemplatesToolStripMenuItem
            // 
            this.editTemplatesToolStripMenuItem.Name = "editTemplatesToolStripMenuItem";
            this.editTemplatesToolStripMenuItem.Size = new System.Drawing.Size(158, 22);
            this.editTemplatesToolStripMenuItem.Text = "Edit templates...";
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.splitContainer1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel1.Location = new System.Drawing.Point(0, 24);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(853, 342);
            this.panel1.TabIndex = 1;
            // 
            // splitContainer1
            // 
            this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer1.Location = new System.Drawing.Point(0, 0);
            this.splitContainer1.Name = "splitContainer1";
            // 
            // splitContainer1.Panel1
            // 
            this.splitContainer1.Panel1.Controls.Add(this.trvConfig);
            // 
            // splitContainer1.Panel2
            // 
            this.splitContainer1.Panel2.Controls.Add(this.txtDisplay);
            this.splitContainer1.Size = new System.Drawing.Size(853, 342);
            this.splitContainer1.SplitterDistance = 284;
            this.splitContainer1.TabIndex = 1;
            // 
            // trvConfig
            // 
            this.trvConfig.CheckBoxes = true;
            this.trvConfig.Dock = System.Windows.Forms.DockStyle.Fill;
            this.trvConfig.Location = new System.Drawing.Point(0, 0);
            this.trvConfig.Name = "trvConfig";
            treeNode1.Name = "PRTGConfigRoot";
            treeNode1.StateImageIndex = 0;
            treeNode1.Text = "PRTG Configuration";
            this.trvConfig.Nodes.AddRange(new System.Windows.Forms.TreeNode[] {
            treeNode1});
            this.trvConfig.Size = new System.Drawing.Size(284, 342);
            this.trvConfig.TabIndex = 1;
            this.trvConfig.AfterSelect += new System.Windows.Forms.TreeViewEventHandler(this.OnTreeViewAfterNodeSelect);
            this.trvConfig.MouseUp += new System.Windows.Forms.MouseEventHandler(this.OnTreeNodeMouseUp);
            // 
            // txtDisplay
            // 
            this.txtDisplay.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtDisplay.Location = new System.Drawing.Point(0, 0);
            this.txtDisplay.Multiline = true;
            this.txtDisplay.Name = "txtDisplay";
            this.txtDisplay.Size = new System.Drawing.Size(565, 342);
            this.txtDisplay.TabIndex = 0;
            // 
            // openFileDialog
            // 
            this.openFileDialog.FileName = "openFileDialog1";
            // 
            // ctxMenuSensorNode
            // 
            this.ctxMenuSensorNode.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.editSingleNodeToolStripMenuItem});
            this.ctxMenuSensorNode.Name = "contextMenuStrip1";
            this.ctxMenuSensorNode.Size = new System.Drawing.Size(162, 48);
            // 
            // editSingleNodeToolStripMenuItem
            // 
            this.editSingleNodeToolStripMenuItem.Name = "editSingleNodeToolStripMenuItem";
            this.editSingleNodeToolStripMenuItem.Size = new System.Drawing.Size(161, 22);
            this.editSingleNodeToolStripMenuItem.Text = "Edit Single Node";
            this.editSingleNodeToolStripMenuItem.Click += new System.EventHandler(this.editSingleNodeToolStripMenuItem_Click);
            // 
            // ctxMenuGroupNode
            // 
            this.ctxMenuGroupNode.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.editGroupNodeToolStripMenuItem});
            this.ctxMenuGroupNode.Name = "ctxMenuGroupNode";
            this.ctxMenuGroupNode.Size = new System.Drawing.Size(163, 26);
            // 
            // editGroupNodeToolStripMenuItem
            // 
            this.editGroupNodeToolStripMenuItem.Name = "editGroupNodeToolStripMenuItem";
            this.editGroupNodeToolStripMenuItem.Size = new System.Drawing.Size(162, 22);
            this.editGroupNodeToolStripMenuItem.Text = "Edit Group Node";
            // 
            // ctxMenuDeviceNode
            // 
            this.ctxMenuDeviceNode.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.editDeviceSensorsToolStripMenuItem});
            this.ctxMenuDeviceNode.Name = "ctxMenuDeviceNode";
            this.ctxMenuDeviceNode.Size = new System.Drawing.Size(174, 26);
            // 
            // editDeviceSensorsToolStripMenuItem
            // 
            this.editDeviceSensorsToolStripMenuItem.Name = "editDeviceSensorsToolStripMenuItem";
            this.editDeviceSensorsToolStripMenuItem.Size = new System.Drawing.Size(173, 22);
            this.editDeviceSensorsToolStripMenuItem.Text = "Edit device sensors";
            // 
            // FormPRTGMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(853, 366);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.menuStrip1);
            this.MainMenuStrip = this.menuStrip1;
            this.Name = "FormPRTGMain";
            this.Text = "PRTG NetFlow Updater";
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            this.splitContainer1.Panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            this.ctxMenuSensorNode.ResumeLayout(false);
            this.ctxMenuGroupNode.ResumeLayout(false);
            this.ctxMenuDeviceNode.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem modeToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem treeViewToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem valueViewToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem loadToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem saveToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem saveAsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.OpenFileDialog openFileDialog;
        private System.Windows.Forms.SplitContainer splitContainer1;
        private System.Windows.Forms.TextBox txtDisplay;
        private System.Windows.Forms.ContextMenuStrip ctxMenuSensorNode;
        private System.Windows.Forms.ToolStripMenuItem templatesToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem editTemplatesToolStripMenuItem;
        private System.Windows.Forms.ContextMenuStrip ctxMenuGroupNode;
        private System.Windows.Forms.ToolStripMenuItem editSingleNodeToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem editGroupNodeToolStripMenuItem;
        private System.Windows.Forms.ContextMenuStrip ctxMenuDeviceNode;
        private System.Windows.Forms.ToolStripMenuItem editDeviceSensorsToolStripMenuItem;
        private TriStateCBTreeView trvConfig;
    }
}

